result/students/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from result.models import Mark, Student, Module
from result import db, mail, session
from flask_mail import Message
import random
from result.students.utils import html_to_pdf, remove_resource
student = Blueprint('student', __name__, template_folder="templates")


def generate_otp():
    otp = random.randint(111111, 999999)
    return otp


class Email:
    def __init__(self, receiver, sender, title, body, html=None, attach=None):
        self.receiver = receiver
        self.sender = sender
        self.title = title
        self.body = body
        self.attach = attach
        self.html = html

    def send_email(self):
        msg = Message(self.title, sender=self.sender,
                      recipients=[self.receiver])
        msg.body = self.body
        msg.html = self.html
        # msg.attach() ---- Feature is about to come
        mail.send(msg)


@student.route('/student')
def get_student():
    return render_template('students/home.html')


@student.route('/get_result', methods=['GET', 'POST'])
def get_result():
    if request.method == 'POST':
        roll_no = request.form.get('roll_no')
        student = Student.query.filter_by(roll_no=roll_no).first()
        if student is None:
            flash('Please Enter Valid Roll No', 'danger')
            return redirect('/get_result')
        email = student.email
        message = Email(email, 'ak475885@gmail.com', 'OTP', session['otp'])
        message.send_email()
        flash('A six digit OTP has been sent to your registered email', 'info')
        return render_template('students/validate.html', roll_no=roll_no)

    return render_template('students/enter_detail.html')


@student.route('/validate/<int:roll_no>', methods=['POST'])
def validate(roll_no):
    if request.method == 'POST':
        user_otp = request.form.get('user_otp')
        if 'otp' in session:
            num = session['otp']
            session.pop('otp', None)
            if num == user_otp:
                mark = Mark.query.filter_by(stu_id=roll_no)
                student = Student.query.filter_by(roll_no=roll_no).first()
                email = student.email
                html = render_template(
                    'students/get_result.html', results=mark)

                html_to_pdf(html, email, roll_no)
                # body = '''Your Password is your Roll_No followed
                #            by characters of your email before '@'
                #            Lets Say Your Roll_No is 45
                #            And Your Email is abc34@example.com
                #             Your Password is 45abc34 '''
                # with student.open_resource("../../out.pdf") as fp:
                #     msg.attach("out.pdf", "application/pdf", fp.read())
                # msg.attach("mark_report", "application/pdf", pdf)

                message = Email(email, 'ak475885@gmail.com', 'Marks_Info',
                                "Your FA1 Result", html)
                message.send_email()
                remove_resource()
                flash("Result has been sent to your Registered Email Id !",
                      "success")
            else:
                flash("Oops you entered wrong OTP! Try Once Again", "danger")

        else:
            flash("Enter Your Roll No", "info")
        return redirect(url_for('student.get_student'))


@student.route('/add_module', methods=['GET', 'POST'])
def add_module():
    if request.method == 'POST':
        roll_no = request.form.get("roll_no")
        subjects = request.form.getlist("sub")
        student = Student.query.get(roll_no)
        if student is None:
            flash('Please Enter Valid Roll No', 'danger')
            return redirect('/add_module')
        for subject in subjects:
            mark = Mark.query.filter_by(stu_id=roll_no, sub_id=subject).first()
            if mark:
                continue
            mark_new = Mark(request.form)
            db.session.add(mark_new)
        db.session.commit()
        flash('Subject Added Successfully', 'success')
        return redirect('/student')
    modules = Module.query.all()
    return render_template('students/subject.html', modules=modules)

    # var = Module.query.all()
    # l = []
    # for subject in var:
    # 	l.append(subject.module_id, subject.module_name)
    # return jsonify(l)

result/students/templates/students/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    <div class="container">
	    {% with messages = get_flashed_messages(with_categories=true) %}
		    {% if messages %}
		       {% for category,msg in messages %}
		          <div class="alert alert-{{ category }}">
		            {{msg}}
		          </div>
		       {% endfor %}
		    {% endif %}
		{% endwith %}
	
		<br>
		<br>
		{% block content %}

		{% endblock %}
	</div>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


</body>
</html>

result/students/templates/students/enter_detail.html
{% extends 'students/base.html' %}

	{% block content %}
       <h1>Enter Roll No</h1>
       <br>
	   <form method='POST'>

	   	   <div class="form-group">

              <label for="roll_no">Enter Roll_No</label>

		   	  <input type="number" id="roll_no" name="roll_no" required="required" placeholder="12345">
		   	  
		   	</div>
		   	  
	   	     <br>
	   	    <button type="submit" class="btn btn-primary">Submit</button>
	   </form>
	{% endblock %}

result/students/templates/students/get_result.html
{% extends 'students/base.html' %}
  
  {% block content %}

	<table>
	    <thead>
	        <tr>
	            <th scope="col">Subject_Name</th>
	            <th scope="col">Marks</th>
	        </tr>
	    </thead>
	    <tbody>
	    	{% for result in results %}
		        <tr>
		            <td>{{result.module.module_name}}</td>
		            <td>{{result.marks}}</td>
		        </tr>
	        {% endfor %}
	    </tbody>
    </table>
   {% endblock %}

result/students/templates/students/home.html
{% extends 'students/base.html' %}

  {% block content %}

     <h1>Welcome Student!</h1>
        <br>
		<ul>

		  <li><a href="{{url_for('student.get_result')}}">Get Result</a></li>
		  <br>
		  <li><a href="{{url_for('student.add_module')}}">Add Subjects</a></li>
        <br>
        <li><a href="{{url_for('main.get_main')}}">Go To User</a></li>
		</ul>

  {% endblock %}

result/students/templates/students/subject.html
{% extends 'students/base.html' %}

{% block content %}	
  <h1> Select Your Subjects</h1>

   <br>

   <form method='POST' id="abc">

   	 <div class="form-group">

              <label for="roll_no">Enter Roll_No</label>

		   	  <input type="number" id="roll_no" name="roll_no" required="required" placeholder="12345">
		   	  
		  </div>
         
         <br>

		  <label for="sub-select">Choose Subjects:</label>
        
			<select name="sub" id="sub-select" form="abc" multiple="True" required="required" class="form-select" multiple aria-label="multiple select example>  
            <br>
				<option value="">--Please choose an option--</option>
			    {% for module in modules %}
			    <option value="{{module.module_id}}">{{module.module_name}}</option>
			    {% endfor %}
			</select>

         <br>

   	  <button type="submit" class="btn btn-primary">Submit</button>

    </form>

{% endblock %}

result/students/templates/students/validate.html
{% extends 'students/base.html' %}

	{% block content %}

	     <form action="{{url_for('student.validate',roll_no=roll_no)}}" method='POST'>
	     	<div class="form-group">
		     	<label for="abc">Enter OTP</label>
		     	<input id ="abc" type="number" name="user_otp" required="required" placeholder="125665">
		    </div>
             <br>
	     	<button type="submit" class="btn btn-primary">Submit</button>
	     </form>

    {% endblock %}